# It's Pangenomes All the Way Down {#hs}

> "I have a strong feeling that the subject of evolution is beautiful without the excuse of creationists needing to be bashed."
>
> --- Richard Dawkins, *Evolutionary biologist*

<span class="newthought">Hierarchical Sets, which will be introduced in this chapter</span>, is an attempt to provide a visualization approach that communicate the relationship between genomes in a pangenome, using native pangenome metrics. The aim has been to replicate the information encoded in the pangenome visualizations based on Venn diagrams, where there is a clear mapping between core, accessory, and singleton sizes and the different areas of circle overlaps. The reason for not using Venn diagrams is that they lack scalability, getting progressively less interpretable above three genomes. Venn diagrams are a natural choice for pangenome data because pangenome data, as well as the core, accessory, and singleton definitions, has clear analogies in set algebra. Thus, it seems that set visualization approaches are a natural fit for pangenome data. Unfortunately, while progress has been made when it comes to scalable set visualizations (see e.g. @Lex:2014fi and @Alsallakh:2013hk), none of the current approaches support the scale made possible by <span class="abr">FindMyFriends</span>. In order to effectively utilize the data encoded in pangenomes containing thousands of genomes it was necessary to develop an entirely new approach to set visualization.

The following article, submitted to [Bioinformatics](http://bioinformatics.oxfordjournals.org), describes the motivation and theory behind the <span class="abr">Hierarchical Sets</span> visualizations and how it relates to pangenome analysis. While the examples in the paper are based on a relatively small pangenome containing 46 genomes, this number of genomes is already outside the usability range of other approaches to set visualization. Chapter&nbsp;4 will show how <span class="abr">Hierarchical Sets</span> scale to much larger pangenomes. Supplementary figures are available in appendix \ref{HSsupfig}.

**Article 3**

[Hierarchical Sets: Analyzing Pangenome Structure through Scalable Set Visualizations](articles/hierarchicalSets.pdf)

The difference between the two visualizations presented in this dissertation is stark. <span class="abr">PanViz</span> is flashy and engaging while <span class="abr">Hierarchical Sets</span> is static and more subdued. This reflects the basic difference between the goals of the two visualizations. The basic mapping between data and visual elements employed in <span class="abr">PanViz</span> are all well defined and the achievement of the visualization is more related to how it uses these prior techniques to describe pangenome data. In the case of <span class="abr">Hierarchical Sets</span> a completely new mapping between a fundamental data entity, a set family, and a visual representation is created. The fact that this mapping is so well-suited for pangenome data is a side-effect of pangenomes having a clear set-algebraic interpretation. I strongly believe that new solutions to fundamental visualization problems, such as the problem of scalable set visualization, should be as bare-bone as possible, optimally avoiding the need for interaction. In this way the visualization can easily be augmented, adapted, or incorporated into other, more specialized, visualizations. <span class="abr">Hierarchical Sets</span> can easily be improved further as a pure pangenome analysis tool, by incorporating domain-specific functionalities, or be used to improve the pangenome overview panel in <span class="abr">PanViz</span>. This would be more difficult if the basic visualization technique required interactions and animations in order to solve its task, such as the case with <span class="abr">Radial Sets</span> [@Alsallakh:2013hk].
